### ISSUE TITLE
Please explain why this is necessary

### ISSUE THREAD

**Issue by yochananmarqos** [blackjackshellac/clippie#8]
What does this do that GPaste 3.40.1 does not? What am I missing?

**Comment by blackjackshellac** [comment]
Well, 3.40 wasn't out when I did it.

And it can search and display the whole clipboard history.

And obfuscate passwords.

Is there really a problem with someone creating a different interface to the backend?

**Comment by yochananmarqos** [comment]
Thank you for the response. I never said there was a problem, I was just perplexed. I genuinely thought I was missing something here.

**Comment by blackjackshellac** [comment]
The other factor was that the GPaste author had said that he wouldn't have a new Gnome 40 version until the summer in one of his messages. I really missed the extension while testing Fedora 34 and Gnome 40 and I was using the command line to access GPaste and figured I'd whip up an extension to just query gpaste-client.  Kind of took off in my head since then.  Also, I'm still pretty new to writing gnome shell extensions and Gtk so I figured it would be a good project.
